name: test setup 7-Zip

on:
  push

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: setup 7-Zip
      uses: drajabr/actions-7-zip-win@main

    - name: check 7z
      shell: cmd
      run: 7z -h

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: test excute with options
      uses: drajabr/actions-7-zip-win@main
      with:
        in: README.md
        out: README.exe
        options: a -sfx

    - name: check excution
      shell: cmd
      run: Dir