name: test setup 7-Zip

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: setup 7-Zip
      uses: milliewalky/setup-7-zip@v1

    - name: check 7-Zip capabilities
      shell: cmd
      run: 7z -h
